apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usmansite
spec:
  selector:
   matchLabels:
     app:static-website
  replicas: 1
  template:
    metadata:
      labels:
        app:static-website
    spec:
      containers:
      - name:static-website
        image: usmansite:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
